name: release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build
    permissions:
      contents: write
    strategy:
      matrix:
        GOOS: [ linux, darwin ]
        GOARCH: [ arm, arm64, amd64 ]
        exclude:
          - GOOS: darwin
            GOARCH: arm
    runs-on: ubuntu-latest
    env:
      executable: pulsemeter-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v6
        with:
          go-version: '^1.25'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}
          fetch-tags: true

      - name: Get the tag
        run: echo "TAG_NAME=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Test
        run: go test -v .

      - name: Build
        run: |
          env GOOS=${{matrix.GOOS}} GOARCH=${{matrix.GOARCH}} go build -ldflags "$LDFLAGS" -v -o ${{env.executable}} .

      - name: Create or update release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ${{env.executable}}
          tag: ${{env.TAG_NAME}}
          omitBodyDuringUpdate: true
